### ISSUE TITLE
Cannot GET /alertmap

### ISSUE THREAD

**Issue by cjramseyer** [johnwalicki/Node-RED-Severe-Weather-Alert-Map#2]
Provide TWC API Key, deployed flow, and can get into dashboard.
Get message 'Cannot GET /alertmap'
Was prompted for credentials multiple times, provided node-red http credentials
Running Node-Red addons for Home Assistant. HA 0.109.6, Node-Red v1.0.5 (from Node-Red menu dropdown.  v6.2.0 of HA plugin for node-red  Running on rPi 3 B+

Help appreciated

**Comment by johnwalicki** [comment]
Hi CJ - Did you solve your issue?
Which version of node-red-contrib-web-worldmap do you have installed?
