### ISSUE TITLE
twc nowcast node api denial

### ISSUE THREAD

**Issue by jpoeppelman1** [johnwalicki/Node-RED-Severe-Weather-Alert-Map#3]
Hello!  When I invoke the twc nowcast node, I get the following permission denial.  Is there something we need to do to fetch the data?  Thank you!

![image](https://user-images.githubusercontent.com/35069890/102888305-7ce8a700-4426-11eb-9da2-34d3294d4411.png)

**Comment by johnwalicki** [comment]
Unfortunately, the TWC API keys designated for Call for Code are suspended until the 2021 challenge kicks off in late 1Q. The TWC terms of service for the free API keys indicated that they would be active from Feb-Nov 2020.   As a result, on 11/30/20 the keys expired.
